### ISSUE TITLE
Cause: project ':mobile' must not be an android project.

### ISSUE THREAD

**Issue by AndrewReitz** [Centril/gradle-plugin-robospock#14]
I have this setup like you mention in https://github.com/Polidea/RoboSpock/issues/28

But keep getting this error. My project is an android project, and I want the tests to be included inside of the main project (which it looks like you can do).

I have tried messing with both the tester and android properties and keep getting this error.

Do I have to have the test project in a separate application?

**Comment by AndrewReitz** [comment]
Looks like this was implemented in #2

Is there an example of setting this up?

**Comment by Centril** [comment]
#2 is no longer supported due to changes in `gradle 2.2` - they won't support creating projects on the fly, see: http://forums.gradle.org/gradle/topics/using-projectbuilder-results-in-cannot-increment-beyond-the-total-of-10

So you'll have to have separate tester & android projects.
However you can always apply the plugin to the android project and just let the tester project contain the `src/` directory without any `build.gradle` file.

In future versions I could always support adding source files to `/android/src/test/` and adding those to the source set of the tester project.

Take a look at: https://github.com/Centril/test-robospock-plugin for a working demo of the plugin, you'll need to bump the version to the latest release tho.

**Comment by AndrewReitz** [comment]
Thanks! Do you want this left open for documentation?

**Comment by Centril** [comment]
It already is documented in [CHANGES.md#1.0.0](../blob/master/CHANGES.md#100) =)
